plugins {
    id 'java'
    id 'com.zeroc.gradle.ice-builder.slice' version '1.5.2'
}

group = 'com.apexstore'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.zeroc:ice:3.7.11'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}